### ISSUE TITLE
Add resources for learning Cryptography

### ISSUE THREAD

**Issue by saty-a** [saty-a/CryptoG#8]
Add resources for learning Cryptography in the resources directory

**Comment by nycanshu** [comment]
Hii i want to do this, can you assign this issue to me. Please

**Comment by nycanshu** [comment]
Hii can you please create one more issue to add cryptography learning resources. Actually i am contributing first time to Hacktoberfest, and i was not aware that only "PR/MRs must be created between October 1 and October 31" will be considered as contribution . so my current contribution is not getting counted currently.
